spring.application.name=gesteam

# Aplicamos la propiedades del fichero application-dev.properties o application-prod.properties
spring.profiles.active=prod

spring.jackson.deserialization.fail-on-unknown-properties=false

# Configuracion de Logs (Guardado en archivo)
logging.file.name=logs/gesteam.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
